import 'bootstrap/dist/css/bootstrap.css'
import Header from '@/Header'
import Menu from '@/Menu'
import Footer from '@/Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Header/>
        <Menu/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
